name: Slither

on:
  push:
    branches:
      - main
    paths:
      - 'contracts/**'
      - '.github/workflows/slither.yml'
  pull_request:

jobs:
  run-slither:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip install slither-analyzer==0.8.1 solc-select==0.2.1

      - name: Dev dependencies
        run: yarn install

      - name: Summary of static analysis
        run: |
          slither . --print human-summary
      - name: Contract summary of static analysis
        run: |
          slither . --print contract-summary
      - name: Function summary
        run: |
          slither . --print function-summary
      - name: Inheritance
        run: |
          slither . --print inheritance
      - name: Data dependency
        run: |
          slither . --print data-dependency